# Generated by Django 4.1.2 on 2022-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l_logs', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topicsno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
